"""The eta x tau grid, which is what separates BDG's controller from raw force.

BDG's field is  num_i = (y - F_i) - eta * e * (F_i - Fbar),  e = (V_b - tau^2)/tau^2.
So `w` scales the WHOLE field -- the mean term and the deviation term together
-- while `eta` reweights the deviation term ALONE. Sweeping eta at FIXED w
therefore holds the force roughly constant and varies only the feedback, and
eta = 0 reduces the field to plug exactly (the pre-registered control).

That matters on Modality 2 specifically, because the applied correction share
(docs/results/M2_SHARE.md) shows bdg pushing ~10x harder than the baselines at
the same w. An in-band gain at 10x the push is not by itself evidence that the
controller is what helped. This table is the evidence.

  python proj1/m2/m2_ablation_grid.py --props gc --md-out docs/results/M2_ABLATION_GRID.md
"""
import argparse
import collections
import glob
import json
import math
import os
import re

ETAS = [0, 1, 2, 4, 8]
TAUS = [0.5, 0.75, 1.0, 1.5]


def mean_se(v):
    m = sum(v) / len(v)
    if len(v) < 2:
        return m, float("nan")
    sd = math.sqrt(sum((x - m) ** 2 for x in v) / (len(v) - 1))
    return m, sd / math.sqrt(len(v))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", default="results/m2")
    ap.add_argument("--n", type=int, default=2000)
    ap.add_argument("--props", default="gc")
    ap.add_argument("--window", type=float, default=0.5)
    ap.add_argument("--md-out", default="docs/results/M2_ABLATION_GRID.md")
    a = ap.parse_args()

    rows = []
    for st in ("m2", "m2abl"):
        for p in glob.glob(os.path.join(a.out_dir, st, "n%d" % a.n, "seed*",
                                        "*.json")):
            rows.append(json.load(open(p)))
    if not rows:
        raise SystemExit("no cells under %s" % a.out_dir)

    ung = {}
    for r in rows:
        if r["arm"] == "unguided":
            ung[(r["prop"], r["seed"])] = r["in_band_fraction"]

    out = []
    for prop in a.props.split(","):
        cells = collections.defaultdict(list)
        chem = collections.defaultdict(list)
        for r in rows:
            if r["prop"] != prop or r["arm"] != "bdg":
                continue
            if abs(r.get("t_min_guide", 0) - a.window) > 1e-9:
                continue
            m = re.match(r"^e([0-9.]+)t([0-9.]+)$", str(r.get("variant")))
            if not m:
                continue
            eta, tau = float(m.group(1)), float(m.group(2))
            u = ung.get((prop, r["seed"]))
            if u is None:
                continue
            cells[(r["w"], tau, eta)].append(r["in_band_fraction"] - u)
            chem[(r["w"], tau, eta)].append(r["kmer_js"])
        # eta = 0 is plug and is tau-independent, so one measurement fills the column
        base = cells.get((1.0, 1.0, 0.0)), cells.get((4.0, 1.0, 0.0))
        for w, b in ((1.0, base[0]), (4.0, base[1])):
            if b:
                for tau in TAUS:
                    cells.setdefault((w, tau, 0.0), b)
        out.append((prop, cells, chem))

    lines = ["# M2 ablation: BDG's two knobs at fixed strength", "",
             "in-band gain over `unguided`, in percentage points, mean over 3 "
             "seeds. Generated by `proj1/m2/m2_ablation_grid.py`; "
             "n=%d, window t >= %g." % (a.n, a.window), "",
             "`w` scales the whole guidance field; `eta` reweights only the "
             "dispersion term. Sweeping `eta` at **fixed `w`** therefore varies "
             "the controller while holding the push roughly constant, and "
             "`eta = 0` is `plug` exactly. This is what distinguishes BDG's "
             "feedback from BDG simply pushing harder -- which matters here "
             "because at equal `w` bdg applies ~10x the correction share of the "
             "baselines (`M2_SHARE.md`).", ""]
    for prop, cells, chem in out:
        lines += ["## %s" % prop, ""]
        for w in (1.0, 4.0):
            lines += ["### w = %g" % w, "",
                      "| tau_mult | " + " | ".join("eta=%g" % e for e in ETAS)
                      + " |", "|---|" + "---|" * len(ETAS)]
            for tau in TAUS:
                cs = []
                for eta in ETAS:
                    v = cells.get((w, tau, float(eta)))
                    cs.append("%+.2f" % (100 * mean_se(v)[0]) if v else "-")
                lines.append("| %g | %s |" % (tau, " | ".join(cs)))
            lines.append("")
    lines += ["## Reading it", "",
              "- **Down a column** (fixed `eta`, varying `tau`): the setpoint. "
              "A `tau_mult` below 1 asks for a tighter spread than the data's "
              "own and concentrates samples toward the target; above 1 asks for "
              "a wider one and disperses them. The sign change across `tau` is "
              "the controller behaving as specified.",
              "- **Across a row** (fixed `tau` and `w`): the feedback gain. A "
              "gain that rises with `eta` at fixed `w` cannot be explained by "
              "force, because `w` is what sets the force.",
              "- **The `eta = 0` column is `plug`**, so every row starts from "
              "the baseline and the whole row is the feedback term's doing.", ""]
    os.makedirs(os.path.dirname(a.md_out) or ".", exist_ok=True)
    open(a.md_out, "w").write("\n".join(lines))
    print("\n".join(lines))
    print("\nwrote %s" % a.md_out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
