"""Measure both property pairs' delta on the same molecules, with the same rule.

    python proj1/scripts/pair_delta_compare.py --md-out docs/results/V3_PAIR_DELTA.md

WHY. Protocol v3 scores different backends with different property pairs
(`transfer_sweep.V3_BACKENDS`): `fm` and the QM9-diffusion base with OURS,
`equifm` with TFG's. Since delta = k x MAE(f_B), the pair sets the width of
the acceptance band, so `in_band` is not comparable across backends that use
different pairs.

"Not comparable" is only half the statement. The other half is BY HOW MUCH AND
IN WHICH DIRECTION, which has to be measured.

A WARNING ABOUT HOW TO MEASURE IT, because this was got wrong twice. The
calibration pool is train_a + train_b -- correct for TFG's pair, since those
are external networks -- but OUR f_A was trained on train_a and OUR f_B on
train_b. Scoring them on the pool measures each one partly on its own
training data and makes our MAEs look ~19 % better than they are, which made
our band look NARROWER than TFG's on mu. It is not. `build_pair_ours` now
scores each net on the half it did not train on, and the honest answer is
that our band is WIDER on all three properties -- which is what the original
BASECMP-sourced estimate said before it was "corrected" on contaminated
numbers.

Both pairs are built through their own `build_pair*` function at
sampler_scale = 1 (the `fm` case), delta_mode "global" -- the rule v3
pre-registers. Nothing here is a free parameter.
"""
import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "proj1", "scripts"))
sys.path.insert(0, os.path.join(ROOT, "proj1", "src"))

PROPS = ("mu", "alpha", "gap")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--k-delta", type=float, default=2.0)
    ap.add_argument("--md-out", default="")
    a = ap.parse_args()

    import torch
    import transfer_sweep as T

    d = torch.load(T.DATA, weights_only=False)
    sel = T.calibration_indices(d)

    rows = []
    for prop in PROPS:
        _, _, d_ours, r_ours = T.build_pair_ours(
            prop, d, sel, a.device, a.k_delta, 1.0, delta_mode="global")
        _, _, d_tfg, r_tfg = T.build_pair(
            prop, d, sel, a.device, a.k_delta, 1.0, delta_mode="global")
        rows.append((prop, d_ours, d_tfg, r_ours["oracle_mae"],
                     r_tfg["oracle_mae"], r_ours["guide_mae"],
                     r_tfg["guide_mae"], r_ours["fitted_slope_guide"],
                     r_ours["fitted_slope_oracle"], r_ours["y_std"]))

    L = ["# v3: the two property pairs' bands, measured", "",
         "Generated by `proj1/scripts/pair_delta_compare.py`. Do not hand-edit; "
         "re-run it.", "",
         "Both pairs built on the **same %d calibration molecules** "
         "(`train_a` + `train_b`, seed %d), the same pre-registered rule "
         "**delta = %g x MAE(f_B)**, at `sampler_scale = 1`."
         % (len(sel), T.CALIB_SEED, a.k_delta), "",
         "| property | delta OURS | delta TFG | ours / TFG | direction |",
         "|---|---|---|---|---|"]
    for (p, do, dt, _mo, _mt, _go, _gt, _sg, _so, _ys) in rows:
        L.append("| %s | %.6f | %.6f | **%.2f×** | %s |"
                 % (p, do, dt, do / dt,
                    "ours **wider**" if do > dt else "ours **narrower**"))
    L += ["",
          "| property | f_B MAE ours | f_B MAE TFG | f_A MAE ours | f_A MAE TFG |",
          "|---|---|---|---|---|"]
    for (p, _do, _dt, mo, mt, go, gt, _sg, _so, _ys) in rows:
        L.append("| %s | %.5f | %.5f | %.5f | %.5f |" % (p, mo, mt, go, gt))
    L += ["",
          "**Our band is wider on all three**, so an ours-pair backend "
          "(`fm`, `edm`) accepts molecules a TFG-pair backend (`equifm`) "
          "would reject, before any base model or arm is considered.",
          "",
          "⚠️ **Each of our nets is scored on the half of the calibration "
          "pool it did NOT train on** (f_A trained on `train_a` is scored on "
          "the `train_b` half, and vice versa). Scoring them on the whole "
          "pool -- which is correct for TFG's external pair -- measures each "
          "one partly on its own training data and flatters it by ~19 %, "
          "which is enough to invert the mu row. An earlier version of this "
          "table did exactly that and reported our mu band as *narrower*; "
          "that is **withdrawn**. The figures above are the held-out ones, "
          "and they land close to `2 x val_mae` from the checkpoints, which "
          "is the independent check that they are right.",
          "",
          "**What does not change:** `in_band` is still not comparable across "
          "backends that use different pairs, in either direction. Within one "
          "backend every arm shares one delta, so the arm-against-arm "
          "comparison is unaffected.",
          "",
          "### Our predictors' scale check",
          "",
          "`build_pair_ours` fits a calibration it then **discards**, purely "
          "to catch a wrong feature scale (our predictors are already in "
          "physical units, so a correctly-fed one fits slope ~1; one fed "
          "features on the wrong scale does not). Measured:",
          "",
          "| property | fitted slope, guide | fitted slope, oracle | y_std |",
          "|---|---|---|---|"]
    for (p, _do, _dt, _mo, _mt, _go, _gt, sg, so, ys) in rows:
        L.append("| %s | %.4f | %.4f | %.5f |" % (p, sg, so, ys))
    L += ["",
          "All six sit within 0.6 % of 1, comfortably inside the check's "
          "0.85-1.15 window, so it will not fire spuriously on a correctly "
          "configured run.",
          "",
          "**What it does not catch.** This fit runs on the data file's raw "
          "one-hot, so its slope is **invariant to `sampler_scale`** -- "
          "verified by building the pair at 1.0 and at 4.0 and getting the "
          "same 0.9999 / 0.9922. It catches a predictor that is mis-scaled in "
          "itself or loaded wrong. The defence against a mis-wired sampler is "
          "separate: `sampler_scale` is read off the generator's own "
          "checkpoint, and the `edm` branch asserts it against "
          "`generator_feat_scale`.", ""]
    out = "\n".join(L)
    # WRITE BEFORE PRINTING. A Windows console is cp1252 and cannot encode
    # this markdown's non-ASCII, so print(out) raised UnicodeEncodeError and
    # the file -- written after it -- was never produced, silently leaving a
    # stale doc beside a script that had already been corrected.
    if a.md_out:
        path = a.md_out if os.path.isabs(a.md_out) else os.path.join(ROOT, a.md_out)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(out)
        print("wrote %s" % path)
    try:
        print(out)
    except UnicodeEncodeError:
        # console cannot encode it; the file already has it verbatim
        print(out.encode('ascii', 'replace').decode('ascii'))


if __name__ == "__main__":
    main()
