"""What BDG's setpoint reaches that the plug-in strength does not.

The v3-final headline says BDG does not beat plug-in on coverage. That is a
statement about coverage *levels*. This script answers a different question, the
one the ablation can actually settle: does the setpoint reach *operating points*
the global strength cannot?

Two comparisons, both at fixed strength so the global force does not move:

  1. The exchange rate. Coverage points gained per point of molecule stability
     lost, for the strength dial (eta = 0, w = 1 -> 4) against the dispersion
     dial (eta = 8, tau_mult = 0.5, w = 1). Both are measured against the same
     eta = 0, w = 1 reference.

  2. The spread ratio R, decoded property standard deviation over unguided's.
     The strength dial only ever contracts (R < 1). The question is whether the
     setpoint reaches R > 1, which would be an operating point no w attains.

Everything is read from the v3-final blade cells. Nothing is quoted from the
n = 5000 run, whose flow-matching cells were guided by a different predictor
pair.

Usage:
  python proj1/scripts/paper_controllability.py \
      --md-out docs/results/PAPER_CONTROLLABILITY.md
"""
from __future__ import annotations

import argparse
import glob
import json
import math
import pathlib
import statistics as st

N_PER_ARM = 6000  # three seeds x n = 2000, pooled
BAR = 2.99  # pre-registered Bonferroni bar, FULL_RUN_V3_PROTOCOL.md 6.1
PROPS = ("mu", "alpha", "gap")


def cells(backend: str, prop: str, arm: str, w: int, stage: str) -> list[dict]:
    pat = (f"results/v3/{backend}/{stage}/n2000/seed*/"
           f"tr__{prop}__{arm}__q50__w{w}__*.json")
    return [json.load(open(f, encoding="utf-8")) for f in sorted(glob.glob(pat))]


def agg(ds: list[dict]) -> dict | None:
    """Seed means of the quantities the paper prints, plus the decoded sd.

    The decoded standard deviation is not stored; it is recovered from the
    decoded RMSE and the decoded bias, which are. Using the continuous sd here
    would silently mix scorings.
    """
    if not ds:
        return None
    out = {
        "ib": st.mean(d["in_band_fraction_dec"] for d in ds),
        "stab": st.mean(d["mol_stability"] for d in ds),
        "n_seeds": len(ds),
    }
    sds = []
    for d in ds:
        rmse = d.get("prop_rmse_eval_dec")
        bias = d.get("f_B_dec_mean", 0.0) - d.get("target_mean", 0.0)
        if rmse is None:
            continue
        var = rmse ** 2 - bias ** 2
        sds.append(math.sqrt(var) if var > 0 else 0.0)
    out["sd"] = st.mean(sds) if sds else float("nan")
    return out


def z_unpaired(p1: float, p2: float) -> float:
    """The pre-registered test: unpaired, separate-variance standard error."""
    se = math.sqrt(p1 * (1 - p1) / N_PER_ARM + p2 * (1 - p2) / N_PER_ARM)
    return (p1 - p2) / se if se > 0 else 0.0


def verdict(z: float) -> str:
    return "above" if z > BAR else ("below" if z < -BAR else "tie")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--md-out", default="docs/results/PAPER_CONTROLLABILITY.md")
    args = ap.parse_args()

    L: list[str] = []
    L.append("# What the setpoint reaches that the strength does not")
    L.append("")
    L.append("Generated by `proj1/scripts/paper_controllability.py`. Do not "
             "hand-edit; re-run it:")
    L.append("")
    L.append("```")
    L.append(f"python proj1/scripts/paper_controllability.py --md-out {args.md_out}")
    L.append("```")
    L.append("")
    L.append("**Source.** v3-final blade cells only: `results/v3/{fm,equifm}/"
             "{v3,v3abl}/n2000/`, seeds 20261001/2/3, n = 2000 per cell pooled "
             f"to N = {N_PER_ARM} per arm, target q50, window t >= 0.5, "
             "100-step Euler. The n = 5000 run is not used: its flow-matching "
             "cells were guided by a different predictor pair.")
    L.append("")
    L.append("**Metric.** Decoded band coverage, which is what the paper "
             "defines as IB. **Test.** Unpaired, separate-variance "
             f"se = sqrt(se_a^2 + se_b^2), bar |z| >= {BAR}.")
    L.append("")
    L.append("**Reading.** The exchange rate is coverage points gained per "
             "point of molecule stability lost, against the same eta = 0, "
             "w = 1 reference. It is a ratio of two measured differences, not "
             "a tested quantity, so it carries no z.")
    L.append("")

    # ---- 1. the exchange rate -------------------------------------------
    L.append("## 1. Coverage per point of chemistry, at fixed strength")
    L.append("")
    L.append("| backend | prop | dial | d IB (pp) | d stab (pp) | IB per stab pt |")
    L.append("|---|---|---|---|---|---|")
    rates: dict[str, list[float]] = {"strength": [], "dispersion": []}
    for be in ("fm", "equifm"):
        for prop in PROPS:
            base = agg(cells(be, prop, "bdg_e0t1", 1, "v3abl"))
            if not base:
                continue
            for label, arm, w in (("strength, w 1->4", "bdg_e0t1", 4),
                                  ("dispersion, eta 8 tau 0.5", "bdg_e8t0.5", 1)):
                c = agg(cells(be, prop, arm, w, "v3abl"))
                if not c:
                    continue
                dib = (c["ib"] - base["ib"]) * 100
                dst = (c["stab"] - base["stab"]) * 100
                rate = dib / abs(dst) if abs(dst) > 0.05 else float("nan")
                key = "strength" if arm == "bdg_e0t1" else "dispersion"
                if not math.isnan(rate):
                    rates[key].append(rate)
                L.append(f"| {be} | {prop} | {label} | {dib:+.2f} | "
                         f"{dst:+.2f} | {rate:.2f} |")
    L.append("")
    for k in ("strength", "dispersion"):
        v = rates[k]
        if v:
            L.append(f"- **{k}**: {min(v):.2f} to {max(v):.2f}, "
                     f"mean {st.mean(v):.2f} over {len(v)} cells")
    L.append("")

    # ---- 2. the spread ratio -------------------------------------------
    L.append("## 2. The spread ratio R against unguided")
    L.append("")
    L.append("R is the decoded property standard deviation divided by the "
             "unguided arm's. R < 1 is a tighter batch, R > 1 a wider one.")
    L.append("")
    L.append("| backend | prop | R, eta 0 w 1 | R, eta 0 w 4 | "
             "R, eta 8 tau 0.5 | R, eta 8 tau 1.5 |")
    L.append("|---|---|---|---|---|---|")
    widen_above_1 = 0
    widen_total = 0
    strength_above_1 = 0
    for be in ("fm", "equifm"):
        for prop in PROPS:
            ung = agg(cells(be, prop, "unguided", 1, "v3"))
            if not ung or not ung["sd"] or math.isnan(ung["sd"]):
                continue
            row = [be, prop]
            for arm, w in (("bdg_e0t1", 1), ("bdg_e0t1", 4),
                           ("bdg_e8t0.5", 1), ("bdg_e8t1.5", 1)):
                c = agg(cells(be, prop, arm, w, "v3abl"))
                r = c["sd"] / ung["sd"] if c else float("nan")
                row.append(f"{r:.2f}")
                if arm == "bdg_e8t1.5":
                    widen_total += 1
                    if r > 1.0:
                        widen_above_1 += 1
                if arm == "bdg_e0t1" and w == 4 and r > 1.0:
                    strength_above_1 += 1
            L.append("| " + " | ".join(row) + " |")
    L.append("")
    L.append(f"- The expanding setpoint reaches R > 1 in "
             f"**{widen_above_1} of {widen_total}** cells.")
    L.append(f"- The strength dial at w = 4 reaches R > 1 in "
             f"**{strength_above_1} of {widen_total}** cells.")
    L.append("")

    # ---- 3. the headline contrasts, for the paper's prose ---------------
    L.append("## 3. The headline contrasts on these cells")
    L.append("")
    counts = {"above": 0, "below": 0, "tie": 0}
    L.append("| backend | prop | arm | IB | plug IB | z | verdict |")
    L.append("|---|---|---|---|---|---|---|")
    for be in ("fm", "equifm"):
        for prop in PROPS:
            pl = agg(cells(be, prop, "plug", 1, "v3"))
            for a in ("bdg_e4t0.5", "bdg_e4t1"):
                c = agg(cells(be, prop, a, 1, "v3"))
                if not c or not pl:
                    continue
                zz = z_unpaired(c["ib"], pl["ib"])
                v = verdict(zz)
                counts[v] += 1
                L.append(f"| {be} | {prop} | `{a}` | {c['ib']:.4f} | "
                         f"{pl['ib']:.4f} | {zz:+.2f} | {v} |")
    L.append("")
    L.append(f"- **BDG against plug-in: {counts['above']} above / "
             f"{counts['below']} below / {counts['tie']} tie** over "
             f"{sum(counts.values())} contrasts.")
    L.append("")

    tfg_above = 0
    tfg_costs = []
    L.append("| backend | prop | tfg IB | plug IB | z | verdict | stab cost (pp) |")
    L.append("|---|---|---|---|---|---|---|")
    for be in ("fm", "equifm"):
        for prop in PROPS:
            t = agg(cells(be, prop, "tfg", 1, "v3"))
            pl = agg(cells(be, prop, "plug", 1, "v3"))
            if not t or not pl:
                continue
            zz = z_unpaired(t["ib"], pl["ib"])
            v = verdict(zz)
            if v == "above":
                tfg_above += 1
            cost = (pl["stab"] - t["stab"]) * 100
            tfg_costs.append(cost)
            L.append(f"| {be} | {prop} | {t['ib']:.4f} | {pl['ib']:.4f} | "
                     f"{zz:+.2f} | {v} | {cost:.1f} |")
    L.append("")
    L.append(f"- **TFG is above plug-in in {tfg_above} of {len(tfg_costs)}** "
             f"cells, at {min(tfg_costs):.0f} to {max(tfg_costs):.0f} points "
             "of molecule stability.")
    L.append("")

    out = pathlib.Path(args.md_out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    print(f"BDG vs plug: {counts['above']}/{counts['below']}/{counts['tie']}")
    print(f"TFG above plug: {tfg_above} of {len(tfg_costs)}")
    for k in ("strength", "dispersion"):
        if rates[k]:
            print(f"{k} exchange rate: {min(rates[k]):.2f}-{max(rates[k]):.2f} "
                  f"(mean {st.mean(rates[k]):.2f})")
    print(f"expanding setpoint R>1 in {widen_above_1}/{widen_total}; "
          f"strength w=4 R>1 in {strength_above_1}/{widen_total}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
