"""Tabulate the joint strength x start-time tune sweep. Read-only, CPU, seconds.

    python proj1/scripts/tune_table.py \
        --root results/tune/n1000 \
        --frozen <scratch>/frozen_tune.json \
        --logs "logs/tune-*.out" \
        --md-out docs/results/TUNE_N1000_RESULTS.md

WHAT IT IS FOR. `freeze_tune.py` picks the two operating points per (property,
arm) and prints the grid; it does not report the full metric block at each
pick, the head-to-heads, or the start-time effect. This script does, from the
same cells, using freeze_tune's OWN load/check/pick functions -- so the picks
here are the freeze's picks by construction, and `--frozen` cross-checks them
against a frozen_tune.json if one is given (it refuses on any disagreement).

WHAT IT REPORTS
  * provenance: cells read vs planned, n, seed, delta (and the v2
    pre-registered delta it replaces), generator, device, non-finite count,
    and -- with --logs -- the SLURM jobs that wrote the cells.
  * per (property, arm), the floor and open picks with the full metric block:
    in_band continuous and decoded, MAE / bias / residual sd over delta (each
    continuous with decoded in brackets), molecule stability, validity,
    uniqueness of valid, the number of candidate cells the pick was the
    maximum of, and grid-edge flags.
  * what the floor costs: open minus floor, in-band and chemistry.
  * each arm's floor pick against unguided and against plug's floor pick.
  * the start-time effect: best in-band at each t_min, a "when vs how"
    range comparison, and every arm at the fixed strength w = 1.
  * the full grid, as an appendix.

BIAS AND RESIDUAL SD come from the cell aggregates, not per-molecule sidecars
(the tune stage ran without --per-mol, so none exist): bias = f_B_mean -
target_mean, sd = sqrt(rmse^2 - bias^2). With a fixed target this is exact --
f_B_mean and prop_rmse_eval are both taken over the finite molecules
(evaluation.evaluate_samples) -- and it is the formula bdg_table.py and
bdg_full_metrics.py already use.

z-SCORES ARE UNPAIRED iid binomial: (p1 - p2) / sqrt(se1^2 + se2^2), se =
sqrt(p(1-p)/n). Every cell was sampled from the same seed (guidance_sweep
reseeds per cell), so two cells share initial noise and sizes; with no
sidecars the pairing cannot be used, and the unpaired se ignores that
correlation.

--md-out: if the file exists, it must hold both BEGIN/END marker pairs below
(main tables, appendix grid); only the text between each pair is replaced and
the hand-written prose around them is kept. If the file does not exist, the two
generated blocks are written as the whole file.
"""
from __future__ import annotations

import argparse
import datetime
import glob
import json
import math
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)

import freeze_tune as ft  # noqa: E402

NL = chr(10)
PROPS = ("mu", "alpha", "gap")
BEGIN = "<!-- BEGIN generated by proj1/scripts/tune_table.py -- do not hand-edit -->"
END = "<!-- END generated by proj1/scripts/tune_table.py -->"
BEGIN_APP = "<!-- BEGIN appendix generated by proj1/scripts/tune_table.py -- do not hand-edit -->"
END_APP = "<!-- END appendix generated by proj1/scripts/tune_table.py -->"
FIXED_W = 1.0
# f_B's residual sd above this many deltas means a handful of molecules score
# absurd property values (finite coordinates, exploded geometry): the MAE and
# sd of that cell are outlier-driven and its in-band sits on broken chemistry.
OUTLIER_SD = 100.0


def se(p, n):
    return math.sqrt(max(p * (1.0 - p), 0.0) / n)


def z(p1, p2, n1, n2):
    s = math.hypot(se(p1, n1), se(p2, n2))
    return float("nan") if s == 0 else (p1 - p2) / s


def fz(v):
    return "--" if v != v else "%+.2f" % v


def expected_max_std_normal(k):
    """E[max of k iid N(0,1)] by numerical integration (Simpson, [-8, 8])."""
    if k <= 1:
        return 0.0
    phi = lambda x: math.exp(-0.5 * x * x) / math.sqrt(2 * math.pi)
    Phi = lambda x: 0.5 * (1.0 + math.erf(x / math.sqrt(2)))
    f = lambda x: x * k * phi(x) * Phi(x) ** (k - 1)
    a, b, m = -8.0, 8.0, 4000
    h = (b - a) / m
    s = f(a) + f(b)
    for i in range(1, m):
        s += (4 if i % 2 else 2) * f(a + i * h)
    return s * h / 3.0


def block(r):
    """The full metric block for one cell, deltas applied."""
    d = float(r["delta"])
    b = float(r["f_B_mean"]) - float(r["target_mean"])
    bd = float(r["f_B_dec_mean"]) - float(r["target_mean"])
    sd = math.sqrt(max(float(r["prop_rmse_eval"]) ** 2 - b * b, 0.0))
    sdd = math.sqrt(max(float(r["prop_rmse_eval_dec"]) ** 2 - bd * bd, 0.0))
    n = int(r["n"])
    ib = float(r["in_band_fraction"])
    return {
        "w": float(r["w"]), "t": float(r["t_min_guide"]), "n": n,
        "ib": ib, "se": se(ib, n), "ibd": float(r["in_band_fraction_dec"]),
        "mae": float(r["prop_mae_eval"]) / d,
        "maed": float(r["prop_mae_eval_dec"]) / d,
        "bias": b / d, "biasd": bd / d, "sd": sd / d, "sdd": sdd / d,
        "ms": float(r["mol_stability"]), "val": float(r["validity"]),
        "uniq": float(r["uniqueness_of_valid"]),
        "uvps": float(r["unique_valid_per_sample"]),
        "clip": int(r.get("clipped_sample_steps", 0)),
        "nonfinite": int(r.get("n_nonfinite", 0)),
    }


def parse_logs(pattern):
    rows = []
    for fn in sorted(glob.glob(pattern if os.path.isabs(pattern)
                               else os.path.join(ROOT, pattern))):
        txt = open(fn, encoding="utf-8", errors="replace").read()
        g = lambda rx: (re.search(rx, txt, re.M).group(1)
                        if re.search(rx, txt, re.M) else None)
        ran = re.findall(r"^(\d+) cells this job, ([\d.]+) min total", txt, re.M)
        disk = re.findall(r"=== cells on disk: (\d+) / (\d+) ===", txt)
        rows.append({
            "file": os.path.basename(fn), "job": g(r"^job\s*:\s*(\S+)"),
            "array": g(r"^array\s*:\s*(.+)$"),
            "cells_run": sum(int(a) for a, _ in ran),
            "minutes": sum(float(b) for _, b in ran),
            "disk": ("%s / %s" % disk[-1]) if disk else "--",
            "rc": g(r"rc=(\d+)"),
            "failed": len(re.findall(r"CELL FAILED", txt)),
            "refused": bool(re.search(r"REFUS|FREEZE", txt)),
        })
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=os.path.join(ROOT, "results", "tune", "n1000"))
    ap.add_argument("--frozen", default="",
                    help="a frozen_tune.json to cross-check the picks against")
    ap.add_argument("--delta-json", default=os.path.join(ROOT, "results", "local_fb_mae.json"))
    ap.add_argument("--logs", default="", help='glob of sweep logs, e.g. "logs/tune-*.out"')
    ap.add_argument("--md-out", default="")
    args = ap.parse_args()
    try:
        sys.stdout.reconfigure(encoding="utf-8")   # the table uses a few non-cp1252 glyphs
    except AttributeError:
        pass

    from guidance_sweep import TUNE_ARMS, TUNE_STRENGTHS, TUNE_WINDOWS
    arms = list(TUNE_ARMS)
    guided = [a for a in arms if a != "unguided"]
    root = args.root if os.path.isabs(args.root) else os.path.join(ROOT, args.root)

    cells, problems = ft.load(root)
    problems = ft.check(cells, problems, list(PROPS), arms, TUNE_STRENGTHS,
                        TUNE_WINDOWS, False)
    dj = json.load(open(args.delta_json if os.path.isabs(args.delta_json)
                        else os.path.join(ROOT, args.delta_json)))
    for p in PROPS:
        u = ft.unguided_of(cells, p)
        if u is not None and abs(float(u["delta"]) - float(dj["delta"][p])) > 1e-12:
            problems.append("%s: cell delta %r is not %s's %r"
                            % (p, u["delta"], args.delta_json, dj["delta"][p]))
    if problems:
        print("REFUSING: the tune tree is not one complete experiment.")
        for q in problems:
            print("  * " + q)
        raise SystemExit(2)

    n_planned = len(PROPS) * (1 + len(guided) * len(TUNE_STRENGTHS) * len(TUNE_WINDOWS))
    any_row = next(iter(cells.values()))
    prov = any_row.get("prov") or {}
    B = {k: block(r) for k, r in cells.items()}
    U = {p: block(ft.unguided_of(cells, p)) for p in PROPS}
    FL = {p: ft.FLOOR * U[p]["ms"] for p in PROPS}
    DELTA = {p: float(ft.unguided_of(cells, p)["delta"]) for p in PROPS}

    # the picks, via freeze_tune's own functions
    P, P_dec, K = {}, {}, {}
    for p in PROPS:
        for a in guided:
            f_r, o_r = ft.pick_for(cells, p, a, FL[p], "in_band_fraction")
            fd, od = ft.pick_for(cells, p, a, FL[p], "in_band_fraction_dec")
            P[(p, a, "floor")], P[(p, a, "open")] = f_r, o_r
            P_dec[(p, a, "floor")], P_dec[(p, a, "open")] = fd, od
            K[(p, a, "floor")] = sum(1 for k, r in cells.items()
                                     if k[0] == p and k[1] == a
                                     and float(r["mol_stability"]) >= FL[p] - 1e-12)
            K[(p, a, "open")] = sum(1 for k in cells if k[0] == p and k[1] == a)

    cross = "not run (no --frozen given)"
    if args.frozen:
        fz_ = json.load(open(args.frozen))
        bad = []
        for (p, a, s), r in P.items():
            fp = (fz_["picks"].get(a) or {}).get(p, {}).get(s)
            mine = None if r is None else (float(r["w"]), float(r["t_min_guide"]))
            theirs = None if fp is None else (float(fp["w"]), float(fp["t_min_guide"]))
            if mine != theirs:
                bad.append("%s/%s %s: here %s, frozen %s" % (p, a, s, mine, theirs))
        if bad:
            print("REFUSING: picks disagree with %s" % args.frozen)
            for b_ in bad:
                print("  * " + b_)
            raise SystemExit(3)
        cross = "all %d picks agree with `%s`" % (len(P), os.path.basename(args.frozen))

    def flags(p, a, s, r):
        out = []
        w, t = float(r["w"]), float(r["t_min_guide"])
        if w >= max(TUNE_STRENGTHS) - 1e-12:
            out.append("w=max")
        if w <= min(TUNE_STRENGTHS) + 1e-12:
            out.append("w=min")
        pk = ft.as_pick(r, FL[p], TUNE_STRENGTHS, TUNE_WINDOWS)
        if ft.flag_window_open_ended(cells, p, a, pk, TUNE_WINDOWS):
            out.append("t-open")
        elif t in (min(TUNE_WINDOWS), max(TUNE_WINDOWS)):
            out.append("t-edge")
        d = P_dec[(p, a, s)]
        if d is not None and (float(d["w"]), float(d["t_min_guide"])) != (w, t):
            out.append("dec!= (w=%g,t=%g)" % (float(d["w"]), float(d["t_min_guide"])))
        if float(r["uniqueness_of_valid"]) < ft.UNIQ_MIN:
            out.append("collapse")
        bb = block(r)
        if bb["nonfinite"]:
            out.append("non-finite=%d" % bb["nonfinite"])
        if bb["sd"] > OUTLIER_SD:
            out.append("f_B outliers (sd>%g d)" % OUTLIER_SD)
        if float(r["mol_stability"]) < FL[p] - 1e-12:
            out.append("below floor")
        tied = ties_of(p, a, s, r)
        if tied:
            out.append("TIE with %s" % "; ".join("w=%g,t=%g" % x for x in tied))
        return ", ".join(out) if out else "--"

    def ties_of(p, a, s, r):
        """Other candidate cells with exactly the pick's in-band: the pick among
        them was decided by the tie-break (smaller w, then larger t_min), not by
        the data."""
        ib = float(r["in_band_fraction"])
        out = []
        for k, c in cells.items():
            if k[0] != p or k[1] != a or c is r:
                continue
            if s == "floor" and float(c["mol_stability"]) < FL[p] - 1e-12:
                continue
            if abs(float(c["in_band_fraction"]) - ib) < 1e-9:
                out.append((float(c["w"]), float(c["t_min_guide"])))
        return sorted(out)

    L = [BEGIN, ""]
    L.append("_Generated %s by `proj1/scripts/tune_table.py` from `%s`._"
             % (datetime.date.today().isoformat(),
                os.path.relpath(root, ROOT).replace(os.sep, "/")))
    L.append("")

    # ---- provenance -------------------------------------------------------
    mt = sorted(os.path.getmtime(os.path.join(root, r["_file"])) for r in cells.values())
    fmt_t = lambda s: datetime.datetime.fromtimestamp(s).strftime("%Y-%m-%d %H:%M")
    L.append("### Provenance (generated)")
    L.append("")
    L.append("| item | value |")
    L.append("|---|---|")
    L.append("| cells read / planned | %d / %d (3 unguided + %d guided arms x 3 properties x %d strengths x %d windows) |"
             % (len(cells), n_planned, len(guided), len(TUNE_STRENGTHS), len(TUNE_WINDOWS)))
    L.append("| `.failed` markers in the tree | %d |"
             % len(glob.glob(os.path.join(root, "*.failed"))))
    L.append("| `frozen_tune.json` in the tree | %s |"
             % ("yes" if os.path.exists(os.path.join(root, "frozen_tune.json")) else "**no**"))
    L.append("| freeze cross-check | %s |" % cross)
    L.append("| n per cell, seed | %s, %s (every cell reseeded with the same seed) |"
             % (any_row["n"], any_row["seed"]))
    L.append("| target | `%s`: %s |" % (any_row["target_name"], ", ".join(
        "%s %.4f" % (p, float(ft.unguided_of(cells, p)["target"])) for p in PROPS)))
    L.append("| in-band delta (this run) | %s |" % ", ".join("%s %.5f" % (p, DELTA[p]) for p in PROPS))
    L.append("| delta source | `%s` (%s) |" % (os.path.basename(args.delta_json), any_row.get("delta_source")))
    L.append("| v2's pre-registered delta (NOT used here) | %s |" % ", ".join(
        "%s %.5f (%+.1f %%)" % (p, float(dj["delta_preregistered"][p]),
                                100.0 * (DELTA[p] / float(dj["delta_preregistered"][p]) - 1.0))
        for p in PROPS))
    L.append("| generator | `%s` md5 `%s` |" % (os.path.basename(str(prov.get("fm_path"))), prov.get("fm_md5")))
    L.append("| device, torch | %s, %s |" % (prov.get("device"), prov.get("torch")))
    L.append("| sampler | %d-step %s, velocity clip %g, batch %d, n_mc %s, sigma_mc %s |"
             % (any_row["steps"], any_row["solver"], any_row["clip"], any_row["batch"],
                any_row.get("n_mc"), any_row.get("sigma_mc")))
    L.append("| strengths | %s |" % ", ".join("%g" % w for w in TUNE_STRENGTHS))
    L.append("| t_min_guide | %s |" % ", ".join("%g" % t for t in TUNE_WINDOWS))
    L.append("| non-finite samples | %d across all cells |" % sum(b["nonfinite"] for b in B.values()))
    L.append("| cell file mtimes (this machine's clock, as preserved by the pull) | %s to %s |"
             % (fmt_t(mt[0]), fmt_t(mt[-1])))
    same_u = len({(round(U[p]["ms"], 12), round(U[p]["val"], 12), round(U[p]["uniq"], 12))
                  for p in PROPS}) == 1
    same_s = len({tuple(ft.unguided_of(cells, p).get("smiles_sample") or []) for p in PROPS}) == 1
    L.append("| unguided cells | %s |" % (
        "one generation scored three ways (identical stability, validity, uniqueness and SMILES sample across properties)"
        if (same_u and same_s) else "**differ across properties** -- check"))
    L.append("")
    if args.logs:
        lg = parse_logs(args.logs)
        L.append("SLURM logs matched by `%s`: %d." % (args.logs, len(lg)))
        L.append("")
        L.append("| log | job | array task | cells run | GPU-min | cells on disk at end | rc | CELL FAILED lines | freeze/refuse text |")
        L.append("|---|---|---|---|---|---|---|---|---|")
        for r in lg:
            L.append("| `%s` | %s | %s | %d | %.1f | %s | %s | %d | %s |"
                     % (r["file"], r["job"], r["array"], r["cells_run"], r["minutes"],
                        r["disk"], r["rc"], r["failed"], "yes" if r["refused"] else "no"))
        L.append("")
        L.append("Total: %d cells run, %.1f GPU-min = %.2f GPU-h."
                 % (sum(r["cells_run"] for r in lg), sum(r["minutes"] for r in lg),
                    sum(r["minutes"] for r in lg) / 60.0))
        L.append("")

    # ---- unguided reference ----------------------------------------------
    L.append("### Unguided reference and the chemistry floor (generated)")
    L.append("")
    L.append("| property | delta | in_band ±se | dec | MAE/d (dec) | bias/d (dec) | resid sd/d (dec) | mol_stab ±se | floor = 0.9 x (±se) | valid | uniq |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for p in PROPS:
        u = U[p]
        s_ms = se(u["ms"], u["n"])
        L.append("| %s | %.5f | %.3f ±%.4f | %.3f | %.2f (%.2f) | %+.2f (%+.2f) | %.2f (%.2f) | %.3f ±%.4f | %.4f (±%.4f) | %.3f | %.3f |"
                 % (p, DELTA[p], u["ib"], u["se"], u["ibd"], u["mae"], u["maed"], u["bias"],
                    u["biasd"], u["sd"], u["sdd"], u["ms"], s_ms, FL[p], ft.FLOOR * s_ms,
                    u["val"], u["uniq"]))
    L.append("")
    L.append("The floor is 0.9 x ONE unguided cell at n = %s, so it carries that cell's sampling error "
             "(the bracketed se)." % any_row["n"])
    L.append("")

    # ---- (a) the picks ----------------------------------------------------
    L.append("### (a) The picks, full metric block (generated)")
    L.append("")
    L.append("`k` = number of candidate cells the pick is the maximum of (floor: cells "
             "clearing the floor; open: all 27). MAE, bias and residual sd are over delta, "
             "continuous with decoded in brackets. Flags: `w=max` / `w=min` = pick at the "
             "top (16) / bottom (0.01) of the strength grid; `t-open` = at an end of the "
             "t_min grid AND beats the neighbouring window at the same w (freeze_tune's "
             "window_edge rule); `t-edge` = at an end of the t_min grid but not rising; "
             "`dec!=` = the decoded metric would pick the cell shown; `collapse` = "
             "uniqueness of valid < %.2f; `below floor` = open pick fails the floor."
             % ft.UNIQ_MIN)
    L.append("")
    for p in PROPS:
        L.append("**%s** (delta %.5f, floor %.4f)" % (p, DELTA[p], FL[p]))
        L.append("")
        L.append("| arm | pick | w | t_min | k | in_band ±se | dec | MAE/d | bias/d | resid sd/d | mol_stab | valid | uniq | flags |")
        L.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        u = U[p]
        L.append("| `unguided` | -- | -- | -- | 1 | %.3f ±%.4f | %.3f | %.2f (%.2f) | %+.2f (%+.2f) | %.2f (%.2f) | %.3f | %.3f | %.3f | reference |"
                 % (u["ib"], u["se"], u["ibd"], u["mae"], u["maed"], u["bias"], u["biasd"],
                    u["sd"], u["sdd"], u["ms"], u["val"], u["uniq"]))
        for a in guided:
            for s in ("floor", "open"):
                r = P[(p, a, s)]
                if r is None:
                    L.append("| `%s` | %s | none | | %d | | | | | | | | | no cell clears the floor |"
                             % (a, s, K[(p, a, s)]))
                    continue
                b = block(r)
                same = (s == "open" and P[(p, a, "floor")] is not None
                        and float(P[(p, a, "floor")]["w"]) == b["w"]
                        and float(P[(p, a, "floor")]["t_min_guide"]) == b["t"])
                L.append("| `%s` | %s%s | %g | %g | %d | %.3f ±%.4f | %.3f | %.2f (%.2f) | %+.2f (%+.2f) | %.2f (%.2f) | %.3f | %.3f | %.3f | %s |"
                         % (a, s, " (= floor)" if same else "", b["w"], b["t"], K[(p, a, s)],
                            b["ib"], b["se"], b["ibd"], b["mae"], b["maed"], b["bias"],
                            b["biasd"], b["sd"], b["sdd"], b["ms"], b["val"], b["uniq"],
                            flags(p, a, s, r)))
        L.append("")

    # tallies over the floor picks, so the prose never counts rows by hand
    fl_picks = [(p, a) for p in PROPS for a in guided if P[(p, a, "floor")] is not None]
    weak = [(p, a) for p, a in fl_picks if float(P[(p, a, "floor")]["w"]) <= 0.05 + 1e-12]
    top = [(p, a) for p, a in fl_picks
           if float(P[(p, a, "floor")]["w"]) >= max(TUNE_STRENGTHS) - 1e-12]
    thin = []
    for p, a in fl_picks:
        ms = float(P[(p, a, "floor")]["mol_stability"])
        s_ms = se(ms, int(P[(p, a, "floor")]["n"]))
        if ms - FL[p] < s_ms:
            thin.append("%s/%s (%.3f vs floor %.4f, se %.4f)" % (p, a, ms, FL[p], s_ms))
    dis = {s: [(p, a) for p in PROPS for a in guided
               if P[(p, a, s)] is not None and P_dec[(p, a, s)] is not None
               and (float(P[(p, a, s)]["w"]), float(P[(p, a, s)]["t_min_guide"]))
               != (float(P_dec[(p, a, s)]["w"]), float(P_dec[(p, a, s)]["t_min_guide"]))]
           for s in ("floor", "open")}
    L.append("Tallies over the %d floor picks:" % len(fl_picks))
    L.append("")
    L.append("- at one of the two weakest strengths (w <= 0.05): %d -- %s"
             % (len(weak), ", ".join("%s/%s" % x for x in weak) or "none"))
    L.append("- at the top of the strength grid while clearing the floor (grid-limited, a lower bound): %d -- %s"
             % (len(top), ", ".join("%s/%s" % x for x in top) or "none"))
    L.append("- clearing the floor by less than one se of the stability proportion: %d -- %s"
             % (len(thin), "; ".join(thin) or "none"))
    tie_list = ["%s/%s %s" % (p, a, s) for p in PROPS for a in guided for s in ("floor", "open")
                if P[(p, a, s)] is not None and ties_of(p, a, s, P[(p, a, s)])]
    L.append("- decided by an exact in-band tie (the tie-break, not the data, chose the cell): %d -- %s"
             % (len(tie_list), ", ".join(tie_list) or "none"))
    L.append("- the decoded in-band would pick a different cell: floor %d (%s); open %d (%s)"
             % (len(dis["floor"]), ", ".join("%s/%s" % x for x in dis["floor"]) or "none",
                len(dis["open"]), ", ".join("%s/%s" % x for x in dis["open"]) or "none"))
    L.append("")

    # ---- (b) cost of the floor -------------------------------------------
    L.append("### (b) What the chemistry floor costs: open minus floor (generated)")
    L.append("")
    L.append("| property | arm | floor in_band | open in_band | open - floor | z | dec: open - floor | floor mol_stab | open mol_stab | stab given up | valid given up | uniq given up | open pick grid-capped? |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for p in PROPS:
        for a in guided:
            fr, orr = P[(p, a, "floor")], P[(p, a, "open")]
            if fr is None or orr is None:
                continue
            f_, o_ = block(fr), block(orr)
            if (f_["w"], f_["t"]) == (o_["w"], o_["t"]):
                L.append("| %s | `%s` | %.3f | %.3f | 0 (same cell) | -- | 0 | %.3f | %.3f | 0 | 0 | 0 | %s |"
                         % (p, a, f_["ib"], o_["ib"], f_["ms"], o_["ms"],
                            "yes" if o_["w"] >= max(TUNE_STRENGTHS) - 1e-12 else "no"))
                continue
            L.append("| %s | `%s` | %.3f | %.3f | %+.3f | %s | %+.3f | %.3f | %.3f | %+.3f | %+.3f | %+.3f | %s |"
                     % (p, a, f_["ib"], o_["ib"], o_["ib"] - f_["ib"],
                        fz(z(o_["ib"], f_["ib"], o_["n"], f_["n"])),
                        o_["ibd"] - f_["ibd"], f_["ms"], o_["ms"], o_["ms"] - f_["ms"],
                        o_["val"] - f_["val"], o_["uniq"] - f_["uniq"],
                        "yes (w=16)" if o_["w"] >= max(TUNE_STRENGTHS) - 1e-12 else "no"))
    L.append("")
    pairs = [(p, a) for p in PROPS for a in guided
             if P[(p, a, "floor")] is not None and P[(p, a, "open")] is not None]
    same_n = sum(1 for p, a in pairs
                 if (float(P[(p, a, "floor")]["w"]), float(P[(p, a, "floor")]["t_min_guide"]))
                 == (float(P[(p, a, "open")]["w"]), float(P[(p, a, "open")]["t_min_guide"])))
    cap_n = sum(1 for p, a in pairs if float(P[(p, a, "open")]["w"]) >= max(TUNE_STRENGTHS) - 1e-12)
    L.append("Tallies over the %d (property, arm) pairs: floor pick = open pick in %d; open pick at "
             "the top of the strength grid (w = %g, so the ceiling is a lower bound) in %d."
             % (len(pairs), same_n, max(TUNE_STRENGTHS), cap_n))
    L.append("")
    for grp, sel in (("excluding `tfg`", lambda a: a != "tfg"), ("`tfg` only", lambda a: a == "tfg")):
        d_ = [(p, a) for p, a in pairs if sel(a)
              and (float(P[(p, a, "floor")]["w"]), float(P[(p, a, "floor")]["t_min_guide"]))
              != (float(P[(p, a, "open")]["w"]), float(P[(p, a, "open")]["t_min_guide"]))]
        if not d_:
            continue
        gib = [block(P[(p, a, "open")])["ib"] - block(P[(p, a, "floor")])["ib"] for p, a in d_]
        gms = [block(P[(p, a, "open")])["ms"] - block(P[(p, a, "floor")])["ms"] for p, a in d_]
        L.append("Where the picks differ (%s, %d pairs): open - floor in-band %+.3f to %+.3f; "
                 "molecule stability given up %+.3f to %+.3f."
                 % (grp, len(d_), min(gib), max(gib), min(gms), max(gms)))
        L.append("")

    # ---- pathology: non-finite samples and f_B outliers --------------------
    L.append("**Cells with non-finite samples or f_B outliers** (residual sd > %g delta), anywhere "
             "in the grid (generated):" % OUTLIER_SD)
    L.append("")
    L.append("| property | arm | w | t_min | non-finite | resid sd/d | MAE/d | guide-eval gap max | in_band | mol_stab | a pick? |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|")
    n_path = 0
    for k in sorted(cells, key=lambda k: (PROPS.index(k[0]), k[1], k[2], k[3])):
        r, b = cells[k], B[k]
        if not (b["nonfinite"] or b["sd"] > OUTLIER_SD):
            continue
        n_path += 1
        tags = [s for s in ("floor", "open") if k[1] != "unguided" and P.get((k[0], k[1], s)) is not None
                and (float(P[(k[0], k[1], s)]["w"]), float(P[(k[0], k[1], s)]["t_min_guide"])) == (k[2], k[3])]
        L.append("| %s | `%s` | %g | %g | %d | %.3g | %.3g | %.3g | %.3f | %.3f | %s |"
                 % (k[0], k[1], k[2], k[3], b["nonfinite"], b["sd"], b["mae"],
                    float(r.get("guide_eval_gap_max", float("nan"))), b["ib"], b["ms"],
                    ", ".join(tags) if tags else "no"))
    L.append("")
    L.append("%d of %d cells." % (n_path, len(cells)))
    L.append("")

    # ---- (c) head-to-heads -----------------------------------------------
    L.append("### (c) Floor picks head-to-head: vs unguided and vs plug's floor pick (generated)")
    L.append("")
    L.append("Unpaired iid z at n = %s per cell, one seed. Screen-level only." % any_row["n"])
    L.append("")
    L.append("| property | arm (floor pick) | in_band | vs unguided: diff | z | dec diff | dec z | stab diff | MAE/d diff | vs plug: diff | z | dec diff | dec z | stab diff |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for p in PROPS:
        u = U[p]
        pl = block(P[(p, "plug", "floor")]) if P[(p, "plug", "floor")] is not None else None
        for a in guided:
            r = P[(p, a, "floor")]
            if r is None:
                L.append("| %s | `%s` | none | | | | | | | | | | | |" % (p, a))
                continue
            b = block(r)
            cu = "%+.3f | %s | %+.3f | %s | %+.3f | %+.2f" % (
                b["ib"] - u["ib"], fz(z(b["ib"], u["ib"], b["n"], u["n"])),
                b["ibd"] - u["ibd"], fz(z(b["ibd"], u["ibd"], b["n"], u["n"])),
                b["ms"] - u["ms"], b["mae"] - u["mae"])
            if a == "plug" or pl is None:
                cp = "-- | -- | -- | -- | --"
            else:
                cp = "%+.3f | %s | %+.3f | %s | %+.3f" % (
                    b["ib"] - pl["ib"], fz(z(b["ib"], pl["ib"], b["n"], pl["n"])),
                    b["ibd"] - pl["ibd"], fz(z(b["ibd"], pl["ibd"], b["n"], pl["n"])),
                    b["ms"] - pl["ms"])
            L.append("| %s | `%s` (w=%g, t=%g) | %.3f | %s | %s |" % (p, a, b["w"], b["t"], b["ib"], cu, cp))
    L.append("")

    # ---- (d) the start-time effect ----------------------------------------
    L.append("### (d) The start-time effect (generated)")
    L.append("")
    L.append("**d1. Best floor-clearing in-band at each t_min** (the strength that achieves it in brackets; "
             "`--` = no cell at that t_min clears the floor). Bold = the arm's floor pick.")
    L.append("")
    hdr = " | ".join("t=%g" % t for t in TUNE_WINDOWS)
    L.append("| property | arm | %s | best - worst t_min | z |" % hdr)
    L.append("|---|---|" + "---|" * len(TUNE_WINDOWS) + "---|---|")
    WHEN = {}
    for p in PROPS:
        for a in guided:
            per_t = {}
            for t in TUNE_WINDOWS:
                c = [r for k, r in cells.items() if k[0] == p and k[1] == a and k[3] == float(t)
                     and float(r["mol_stability"]) >= FL[p] - 1e-12]
                per_t[t] = ft.best(c, "in_band_fraction") if c else None
            fr = P[(p, a, "floor")]
            txt = []
            for t in TUNE_WINDOWS:
                r = per_t[t]
                if r is None:
                    txt.append("--")
                    continue
                s_ = "%.3f (w=%g)" % (float(r["in_band_fraction"]), float(r["w"]))
                if fr is not None and float(fr["w"]) == float(r["w"]) and float(fr["t_min_guide"]) == float(t):
                    s_ = "**%s**" % s_
                txt.append(s_)
            got = [r for r in per_t.values() if r is not None]
            if len(got) >= 2:
                hi = max(got, key=lambda r: float(r["in_band_fraction"]))
                lo = min(got, key=lambda r: float(r["in_band_fraction"]))
                rng = float(hi["in_band_fraction"]) - float(lo["in_band_fraction"])
                zz = z(float(hi["in_band_fraction"]), float(lo["in_band_fraction"]), int(hi["n"]), int(lo["n"]))
                WHEN[(p, a)] = (rng, zz, [float(r["in_band_fraction"]) for r in got])
                tail = "%+.3f | %s" % (rng, fz(zz))
            else:
                tail = "-- | --"
            L.append("| %s | `%s` | %s | %s |" % (p, a, " | ".join(txt), tail))
    L.append("")

    L.append("**d2. Best unconstrained in-band at each t_min** (strength in brackets; mol_stab after the slash).")
    L.append("")
    L.append("| property | arm | %s |" % hdr)
    L.append("|---|---|" + "---|" * len(TUNE_WINDOWS))
    hi_t = {t: 0 for t in TUNE_WINDOWS}
    lo_t = {t: 0 for t in TUNE_WINDOWS}
    for p in PROPS:
        for a in guided:
            txt, vals = [], {}
            for t in TUNE_WINDOWS:
                c = [r for k, r in cells.items() if k[0] == p and k[1] == a and k[3] == float(t)]
                r = ft.best(c, "in_band_fraction")
                vals[t] = float(r["in_band_fraction"])
                txt.append("%.3f (w=%g) / %.3f" % (float(r["in_band_fraction"]), float(r["w"]),
                                                    float(r["mol_stability"])))
            L.append("| %s | `%s` | %s |" % (p, a, " | ".join(txt)))
            hi_t[max(vals, key=lambda t: vals[t])] += 1
            lo_t[min(vals, key=lambda t: vals[t])] += 1
    L.append("")
    L.append("Which start time gives the highest / lowest unconstrained ceiling, over the %d pairs: "
             "highest %s; lowest %s." % (len(PROPS) * len(guided),
                                         ", ".join("t=%g: %d" % (t, hi_t[t]) for t in TUNE_WINDOWS),
                                         ", ".join("t=%g: %d" % (t, lo_t[t]) for t in TUNE_WINDOWS)))
    L.append("")

    L.append("**d3. When vs how, inside the chemistry floor.** For each arm, among floor-clearing cells only: "
             "*when* = best in-band at the best t_min minus best in-band at the worst t_min (each t_min at its "
             "own best strength; from d1). *how* = the same range taken over strengths (each strength at its "
             "own best t_min; strengths with no floor-clearing cell are skipped). z is the unpaired z of the "
             "two cells that define each range. **The two ranges are NOT directly comparable:** *when* is a "
             "range over at most %d groups and *how* over up to %d, and the range of more noisy draws is "
             "larger by construction. So each range is set against an illustrative noise null for its own "
             "number of groups k: the expected range of k iid normal draws, 2 x E[max of k N(0,1)] x se, with "
             "se = sqrt(p(1-p)/n) at p = the mean of the k group maxima. It treats the group maxima as iid "
             "draws with one true in-band, which they are not (they are themselves maxima, and share a seed), "
             "so it is a yardstick, not a test."
             % (len(TUNE_WINDOWS), len(TUNE_STRENGTHS)))
    L.append("")
    L.append("| property | arm | when: range | z | k | null range | how: range | z | k | null range |")
    L.append("|---|---|---|---|---|---|---|---|---|---|")
    n_cell = int(any_row["n"])

    def null_range(vals):
        if len(vals) < 2:
            return float("nan")
        pbar = sum(vals) / len(vals)
        return 2.0 * expected_max_std_normal(len(vals)) * se(pbar, n_cell)

    above = {"when": 0, "how": 0}
    zmax = {"when": (0.0, ""), "how": (0.0, "")}
    for p in PROPS:
        for a in guided:
            per_w = {}
            for w in TUNE_STRENGTHS:
                c = [r for k, r in cells.items() if k[0] == p and k[1] == a and k[2] == float(w)
                     and float(r["mol_stability"]) >= FL[p] - 1e-12]
                if c:
                    per_w[w] = ft.best(c, "in_band_fraction")
            if len(per_w) >= 2:
                hi = max(per_w.values(), key=lambda r: float(r["in_band_fraction"]))
                lo = min(per_w.values(), key=lambda r: float(r["in_band_fraction"]))
                hr = float(hi["in_band_fraction"]) - float(lo["in_band_fraction"])
                hz = z(float(hi["in_band_fraction"]), float(lo["in_band_fraction"]), int(hi["n"]), int(lo["n"]))
            else:
                hr, hz = float("nan"), float("nan")
            wr, wz, wvals = WHEN.get((p, a), (float("nan"), float("nan"), []))
            hvals = [float(r["in_band_fraction"]) for r in per_w.values()]
            wn, hn = null_range(wvals), null_range(hvals)
            for lab, rng_, nul, zz_ in (("when", wr, wn, wz), ("how", hr, hn, hz)):
                if rng_ == rng_ and nul == nul and rng_ > nul:
                    above[lab] += 1
                if zz_ == zz_ and zz_ > zmax[lab][0]:
                    zmax[lab] = (zz_, "%s/%s" % (p, a))
            L.append("| %s | `%s` | %s | %s | %d | %s | %s | %s | %d | %s |"
                     % (p, a, "--" if wr != wr else "%+.3f" % wr, fz(wz), len(wvals),
                        "--" if wn != wn else "%.3f" % wn,
                        "--" if hr != hr else "%+.3f" % hr, fz(hz), len(hvals),
                        "--" if hn != hn else "%.3f" % hn))
    L.append("")
    L.append("Over the %d (property, arm) pairs: the largest *when* z is %+.2f (%s) and the largest *how* z is "
             "%+.2f (%s); a range exceeds its noise null in %d pairs for *when* and %d for *how*."
             % (len(PROPS) * len(guided), zmax["when"][0], zmax["when"][1], zmax["how"][0],
                zmax["how"][1], above["when"], above["how"]))
    L.append("")
    tf = {t: sum(1 for p in PROPS for a in guided if P[(p, a, "floor")] is not None
                 and float(P[(p, a, "floor")]["t_min_guide"]) == float(t)) for t in TUNE_WINDOWS}
    to = {t: sum(1 for p in PROPS for a in guided if P[(p, a, "open")] is not None
                 and float(P[(p, a, "open")]["t_min_guide"]) == float(t)) for t in TUNE_WINDOWS}
    L.append("Where the picks land in t_min, over the %d (property, arm) pairs: floor picks %s; open picks %s."
             % (len(PROPS) * len(guided),
                ", ".join("t=%g: %d" % (t, tf[t]) for t in TUNE_WINDOWS),
                ", ".join("t=%g: %d" % (t, to[t]) for t in TUNE_WINDOWS)))
    L.append("")

    L.append("**d4. Every arm at the fixed strength w = %g, across t_min** -- the shape of the "
             "project's original window comparison (one strength, several start times). Each cell: "
             "in_band (z vs unguided) / MAE/d / mol_stab." % FIXED_W)
    L.append("")
    L.append("| property | arm | %s |" % hdr)
    L.append("|---|---|" + "---|" * len(TUNE_WINDOWS))
    for p in PROPS:
        u = U[p]
        for a in guided:
            txt = []
            for t in TUNE_WINDOWS:
                r = cells.get((p, a, FIXED_W, float(t)))
                if r is None:
                    txt.append("--")
                    continue
                b = block(r)
                txt.append("%.3f (%s) / %.2f / %.3f" % (b["ib"], fz(z(b["ib"], u["ib"], b["n"], u["n"])),
                                                       b["mae"], b["ms"]))
            L.append("| %s | `%s` | %s |" % (p, a, " | ".join(txt)))
    L.append("")

    # ---- resolving power / winner's curse ---------------------------------
    L.append("### Resolving power and selection bias (generated)")
    L.append("")
    L.append("| property | unguided in_band | its se at n = %s | se of a difference of two such cells |" % any_row["n"])
    L.append("|---|---|---|---|")
    for p in PROPS:
        L.append("| %s | %.3f | %.4f | %.4f |" % (p, U[p]["ib"], U[p]["se"], math.sqrt(2) * U[p]["se"]))
    L.append("")
    ks = sorted({K[k] for k in K} | {27})
    L.append("Expected maximum of k iid N(0, 1) draws (the upward bias of a pick, in se units, if all k "
             "candidates had the same true in-band and were independent; the cells share a seed, so this "
             "is an illustration, not a correction): " +
             ", ".join("k=%d: %.2f" % (k, expected_max_std_normal(k)) for k in ks) + ".")
    L.append("")
    L.append("Candidate-set sizes seen at the floor picks: %s."
             % ", ".join("%s/%s %d" % (p, a, K[(p, a, "floor")]) for p in PROPS for a in guided))
    L.append("")

    L.append(END)

    # ---- appendix: full grid (its own marker pair) ------------------------
    A = [BEGIN_APP, ""]
    A.append("### Appendix: the full grid (generated)")
    A.append("")
    A.append("Each cell: `in_band (dec) / mol_stab`. **Bold** = clears the floor. `[F]` floor pick, `[O]` open pick.")
    A.append("")
    for p in PROPS:
        A.append("**%s** (floor %.4f; unguided %.3f (%.3f) / %.3f)" % (p, FL[p], U[p]["ib"], U[p]["ibd"], U[p]["ms"]))
        A.append("")
        for a in guided:
            A.append("`%s`" % a)
            A.append("")
            A.append("| w \\ t_min | " + " | ".join("%g" % t for t in TUNE_WINDOWS) + " |")
            A.append("|---|" + "---|" * len(TUNE_WINDOWS))
            for w in TUNE_STRENGTHS:
                row = []
                for t in TUNE_WINDOWS:
                    r = cells.get((p, a, float(w), float(t)))
                    if r is None:
                        row.append("--")
                        continue
                    b = block(r)
                    s_ = "%.3f (%.3f) / %.3f" % (b["ib"], b["ibd"], b["ms"])
                    if b["ms"] >= FL[p] - 1e-12:
                        s_ = "**%s**" % s_
                    for which, tag in (("floor", "F"), ("open", "O")):
                        x = P[(p, a, which)]
                        if x is not None and float(x["w"]) == float(w) and float(x["t_min_guide"]) == float(t):
                            s_ += " `[%s]`" % tag
                    row.append(s_)
                A.append("| %g | %s |" % (w, " | ".join(row)))
            A.append("")
    A.append(END_APP)

    main_txt = NL.join(L)
    app_txt = NL.join(A)
    if not args.md_out:
        print(main_txt + NL + NL + app_txt)
        return
    dst = args.md_out if os.path.isabs(args.md_out) else os.path.join(ROOT, args.md_out)
    if os.path.exists(dst):
        old = open(dst, encoding="utf-8").read()
        new = old
        for b_, e_, t_ in ((BEGIN, END, main_txt), (BEGIN_APP, END_APP, app_txt)):
            if b_ not in new or e_ not in new:
                raise SystemExit("%s exists but lacks the marker pair %s ... %s; refusing "
                                 "to overwrite it" % (dst, b_, e_))
            head, rest = new.split(b_, 1)
            _, tail = rest.split(e_, 1)
            new = head + t_ + tail
        open(dst, "w", encoding="utf-8").write(new)
        print("spliced both generated blocks into %s" % dst)
        return
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    open(dst, "w", encoding="utf-8").write(main_txt + NL + NL + app_txt + NL)
    print("wrote %s" % dst)


if __name__ == "__main__":
    main()
