"""What the blade v3 run (n = 2000) says that its generated tables do not print,
and whether it agrees with the Betty v3 headline (n = 5000).

    python proj1/scripts/v3_blade_readout.py --md-out docs/results/V3_BLADE_READOUT.md

WHY THIS EXISTS. The blade run's README section (commit 23e8813) leads with
"BDG beats DPS by +0.95 pp in-band, paired, t = 5.71 over 18 pairs". No
generated table prints that number, so this script derives it from the cells,
prints the per-cell contrast beside it at the protocol's own bar, prints the
ablation grid the README's "tau reverses sign" claim rests on, and checks the
blade run against the Betty run that preceded it.

WHAT IT READS -- committed stats JSONs only, through v3_table's loader:
  results/v3/<be>/v3/n2000/seed*/      blade headline  (fm, equifm, edm)
  results/v3/<be>/v3abl/n2000/seed*/   blade ablation  (fm, equifm; w in {1,4})
  results/v3/<be>/n5000/seed*/         Betty headline  (flat tree; fm, equifm)

WHAT IT DOES NOT COMPUTE. Useful yield (decoded in-band AND stable, per
molecule) needs the *.permol.pt sidecars, which stay on blade. v3_paired.py
computes it there; see the doc this writes for the command.

STATISTICS. Contrasts are UNPAIRED, se = sqrt(p(1-p)/N) per arm with N = 3n,
as FULL_RUN_V3_PROTOCOL.md section 6.1 pre-registers, and verdicts are called at
its Bonferroni bar z = 2.99. Unpaired is conservative (arms share initial
noise), so a tie here can be a paired win; the paired reading is v3_paired.py's.
"""
from __future__ import annotations

import argparse
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)

import v3_table as V                                   # noqa: E402

NL = chr(10)
PROPS = V.PROPS
SEEDS = ["20261001", "20261002", "20261003"]
ZBAR = 2.99                     # FULL_RUN_V3_PROTOCOL.md:582
BDG_HEAD = ("bdg_e4t0.5", "bdg_e4t1")
ETAS = (0, 1, 2, 4, 8)
TAUS = ("0.5", "0.75", "1", "1.5")


def arm_name(eta, tau):
    return "bdg_e0t1" if eta == 0 else "bdg_e%dt%s" % (eta, tau)


def load(root, be, n, stage, w=None, layout="staged"):
    cells, problems = V.load(root, be, n, SEEDS, stage=stage, w=w, layout=layout)
    if problems:
        sys.exit("refusing: %s/%s n%d: %s" % (be, stage, n, "; ".join(problems)))
    return cells


def se(p, N):
    return math.sqrt(max(p * (1 - p), 0.0) / N)


def zdiff(pa, pb, Na, Nb):
    s = math.sqrt(se(pa, Na) ** 2 + se(pb, Nb) ** 2)
    return (pa - pb) / s if s > 0 else float("nan")


def verdict(z):
    return "above" if z >= ZBAR else ("below" if z <= -ZBAR else "tie")


def pp(x):
    return "%+.2f" % (100 * x)


def mean(xs):
    return sum(xs) / len(xs)


def sd(xs):
    m = mean(xs)
    return math.sqrt(sum((x - m) ** 2 for x in xs) / (len(xs) - 1))


def o2(rows):
    """Second-oracle (OC-Flow, its own delta) in-band, pooled over seeds."""
    return sum(r["oracle2"]["in_band"] * r["n"] for r in rows) / sum(r["n"] for r in rows)


def w_eff(rows):
    """Measured deviation gain, mean over seeds (v3_table's pooled() reads seed 1 only)."""
    v = [(r.get("diag") or {}).get("bdg_w_eff") for r in rows]
    v = [x for x in v if x is not None]
    return mean(v) if v else None


def ranks(xs):
    order = sorted(range(len(xs)), key=lambda i: xs[i])
    r = [0.0] * len(xs)
    i = 0
    while i < len(order):
        j = i
        while j + 1 < len(order) and xs[order[j + 1]] == xs[order[i]]:
            j += 1
        for k in range(i, j + 1):
            r[order[k]] = (i + j) / 2.0 + 1
        i = j + 1
    return r


def spearman(a, b):
    ra, rb = ranks(a), ranks(b)
    ma, mb = mean(ra), mean(rb)
    num = sum((x - ma) * (y - mb) for x, y in zip(ra, rb))
    den = math.sqrt(sum((x - ma) ** 2 for x in ra) * sum((y - mb) ** 2 for y in rb))
    return num / den if den else float("nan")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=os.path.join(ROOT, "results", "v3"))
    ap.add_argument("--md-out", default="")
    args = ap.parse_args()
    R = args.root

    head = {be: load(R, be, 2000, "v3") for be in ("fm", "equifm", "edm")}
    abl = {(be, w): load(R, be, 2000, "v3abl", w=w)
           for be in ("fm", "equifm") for w in (1, 4)}
    betty = {be: load(R, be, 5000, "v3", layout="flat") for be in ("fm", "equifm")}
    P = lambda cells, prop, arm: V.pooled(cells[(prop, arm)])

    L = []
    A = L.append
    A("# v3 on blade (n = 2000): the BDG contrast, the ablation grid, and the Betty cross-check")
    A("")
    A("Generated by `proj1/scripts/v3_blade_readout.py`. Do not hand-edit; re-run it:")
    A("")
    A("```")
    A("python proj1/scripts/v3_blade_readout.py --md-out docs/results/V3_BLADE_READOUT.md")
    A("```")
    A("")
    A("**Sources** (committed stats JSONs only): blade headline `results/v3/<be>/v3/n2000/` "
      "(fm, equifm, edm; %d cells), blade ablation `results/v3/<be>/v3abl/n2000/` "
      "(fm, equifm; w = 1 and 4; %d cells), Betty headline `results/v3/<be>/n5000/` "
      "(flat tree, fm and equifm; %d cells). Seeds %s. Target q50, window t >= 0.5, "
      "100-step Euler, batch 500."
      % (sum(len(rs) for c in head.values() for rs in c.values()),
         sum(len(rs) for c in abl.values() for rs in c.values()),
         sum(len(rs) for c in betty.values() for rs in c.values()),
         ", ".join(SEEDS)))
    A("")
    A("**Statistics.** Every contrast is **unpaired**, se = sqrt(p(1-p)/N) per arm with "
      "N = 3n, and verdicts are called at the **pre-registered** Bonferroni bar "
      "**z = %.2f** (FULL_RUN_V3_PROTOCOL.md section 6.1). Unpaired is conservative "
      "by roughly sqrt(2), since arms in one (backend, property, seed) share their "
      "initial noise: a tie here can be a paired win. **Useful yield is not computed** "
      "(it needs the per-molecule sidecars, which stay on blade); everything below is "
      "continuous or decoded in-band beside the chemistry it cost." % ZBAR)
    A("")

    # ------------------------------------------------------------ 1. per cell
    A("## 1. BDG against `plug`, per cell, at the pre-registered bar")
    A("")
    A("`plug` is BDG at eta = 0, so it is the base arm for the dispersion term. "
      "Both headline BDG arms are shown; the README's figure uses only `bdg_e4t0.5`.")
    A("")
    A("| backend | prop | arm | in_band BDG / plug | d cont (pp) | z | d dec (pp) | z dec "
      "| d oracle2 (pp) | z o2 | seeds BDG > plug | d mol_stab (pp) | d validity (pp) "
      "| verdict cont / dec / o2 |")
    A("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    tally = {}
    for be in ("fm", "equifm"):
        for prop in PROPS:
            pl = P(head[be], prop, "plug")
            plr = head[be][(prop, "plug")]
            for arm in BDG_HEAD:
                b = P(head[be], prop, arm)
                br = head[be][(prop, arm)]
                d = b["in_band_fraction"] - pl["in_band_fraction"]
                z = zdiff(b["in_band_fraction"], pl["in_band_fraction"], b["N"], pl["N"])
                dd = b["in_band_fraction_dec"] - pl["in_band_fraction_dec"]
                zd = zdiff(b["in_band_fraction_dec"], pl["in_band_fraction_dec"], b["N"], pl["N"])
                pos = sum(1 for x, y in zip(br, plr)
                          if x["in_band_fraction"] > y["in_band_fraction"])
                ob, op = o2(br), o2(plr)
                zo = zdiff(ob, op, b["N"], pl["N"])
                vc, vd, vo = verdict(z), verdict(zd), verdict(zo)
                tally.setdefault(arm, {"cont": [], "dec": [], "o2": []})
                tally[arm]["cont"].append(vc)
                tally[arm]["dec"].append(vd)
                tally[arm]["o2"].append(vo)
                A("| %s | %s | `%s` | %.4f / %.4f | %s | %+.2f | %s | %+.2f | %s | %+.2f | %d of 3 | %s | %s | %s / %s / %s |"
                  % (be, prop, arm, b["in_band_fraction"], pl["in_band_fraction"],
                     pp(d), z, pp(dd), zd, pp(ob - op), zo, pos,
                     pp(b["mol_stability"] - pl["mol_stability"]),
                     pp(b["validity"] - pl["validity"]), vc, vd, vo))
    A("")
    for arm in BDG_HEAD:
        for k in ("cont", "dec", "o2"):
            v = tally[arm][k]
            A("- `%s` vs `plug`, %s in-band, 6 cells: **%d above / %d below / %d tie**."
              % (arm, {"cont": "continuous", "dec": "decoded",
                       "o2": "second-oracle (OC-Flow, own delta)"}[k],
                 v.count("above"), v.count("below"), v.count("tie")))
    A("")

    # ------------------------------------------------------------ 2. pooled
    A("## 2. The README's pooled figure, reproduced, and what it is")
    A("")
    A("The README's \"+0.95 pp, t = 5.71 over 18 pairs\" is the mean over the 18 "
      "(backend, property, seed) cells of fm and equifm of `bdg_e4t0.5` minus `plug` on "
      "**continuous** in-band, with a one-sample t on those 18 differences (df = 17).")
    A("")
    A("| contrast | metric | mean d (pp) | sd (pp) | t (df 17) | fm mean | equifm mean | cells > 0 |")
    A("|---|---|---|---|---|---|---|---|")
    for arm in BDG_HEAD:
        for key, lab in (("in_band_fraction", "continuous"), ("in_band_fraction_dec", "decoded")):
            ds, per = [], {}
            for be in ("fm", "equifm"):
                for prop in PROPS:
                    for x, y in zip(head[be][(prop, arm)], head[be][(prop, "plug")]):
                        ds.append(x[key] - y[key])
                        per.setdefault(be, []).append(x[key] - y[key])
            t = mean(ds) / (sd(ds) / math.sqrt(len(ds)))
            A("| `%s` - `plug` | %s | %s | %.2f | %+.2f | %s | %s | %d of %d |"
              % (arm, lab, pp(mean(ds)), 100 * sd(ds), t, pp(mean(per["fm"])),
                 pp(mean(per["equifm"])), sum(1 for x in ds if x > 0), len(ds)))
    A("")
    ch = {}
    for be in ("fm", "equifm", "edm"):
        for prop in PROPS:
            u = P(head[be], prop, "unguided")["mol_stability"]
            for arm in ("plug",) + BDG_HEAD:
                if (prop, arm) in head[be]:
                    ch.setdefault((arm, be), []).append(P(head[be], prop, arm)["mol_stability"] - u)
    six = lambda arm: ch[(arm, "fm")] + ch[(arm, "equifm")]
    A("**Chemistry, on matched cells.** Mean change in molecule stability against "
      "`unguided`: `bdg_e4t0.5` **%s pp** and `bdg_e4t1` %s pp over fm + equifm (6 cells); "
      "`plug` **%s pp over the same 6 cells**, and %s pp if edm's 3 plug cells are "
      "added (9 cells). edm plans no BDG arm, so only the 6-cell figure is a like-for-like "
      "comparison."
      % (pp(mean(six("bdg_e4t0.5"))), pp(mean(six("bdg_e4t1"))), pp(mean(six("plug"))),
         pp(mean(six("plug") + ch[("plug", "edm")]))))
    A("")
    A("**How to read the pooled t.** It asks whether the difference has a consistent "
      "sign across 18 cells that pool three properties, two base models and two bands; "
      "it is not the protocol's per-cell test, it was not pre-registered, and it uses the "
      "better of the two headline BDG arms. Section 1 is the pre-registered reading. "
      "The protocol also says (section 6.2) that from the headline alone `bdg - plug` "
      "cannot separate controlling spread from pushing harder: the measured w_eff of "
      "`bdg_e4t0.5` is above 1 (it up-weights the deviation term) and its clipped steps "
      "run several times plug's (V3_RESULTS.md, cost tables).")
    A("")

    # ------------------------------------------------------------ 3. ablation
    A("## 3. The ablation grid: in-band against the eta = 0 cell, at fixed w")
    A("")
    A("Each entry is **d in_band (pp) against `bdg_e0t1`** (eta = 0, which is `plug`'s "
      "field) in the same stage, strength and seeds, followed by the **measured w_eff** "
      "(mean over seeds and guided steps). Along a row w is fixed, so the global strength "
      "does not change; only the deviation gain does.")
    A("")
    summ = []
    for be in ("fm", "equifm"):
        for prop in PROPS:
            for w in (1, 4):
                c = abl[(be, w)]
                base = P(c, prop, "bdg_e0t1")
                b0 = base["in_band_fraction"]
                A("**%s / %s / w = %d** (eta = 0: in_band %.4f, mol_stab %.4f)"
                  % (be, prop, w, b0, base["mol_stability"]))
                A("")
                A("| tau_mult \\ eta | " + " | ".join(str(e) for e in ETAS[1:]) + " |")
                A("|---|" + "---|" * (len(ETAS) - 1))
                xs, ys = [], []
                rowvals = {}
                for tau in TAUS:
                    cells = []
                    for eta in ETAS[1:]:
                        a = arm_name(eta, tau)
                        p = P(c, prop, a)
                        d = p["in_band_fraction"] - b0
                        we = w_eff(c[(prop, a)])
                        xs.append(we)
                        ys.append(d)
                        rowvals.setdefault(tau, []).append((eta, d, p, we))
                        cells.append("%s / %.2f" % (pp(d), we))
                    A("| %s | %s |" % (tau, " | ".join(cells)))
                A("")
                r05 = [d for (_e, d, _p, _w) in rowvals["0.5"]]
                mono = all(r05[i + 1] >= r05[i] for i in range(len(r05) - 1)) and r05[0] >= 0
                e8a = rowvals["0.5"][-1]
                e8b = rowvals["1.5"][-1]
                summ.append((be, prop, w, mono,
                             e8a[1], zdiff(e8a[2]["in_band_fraction"], b0, e8a[2]["N"], base["N"]),
                             e8a[2]["mol_stability"] - base["mol_stability"],
                             e8b[1], zdiff(e8b[2]["in_band_fraction"], b0, e8b[2]["N"], base["N"]),
                             spearman(xs, ys)))
    A("### Summary over the 12 grids")
    A("")
    A("| backend | prop | w | tau 0.5 row rises with eta | d at e8 t0.5 (pp) | z | its d mol_stab (pp) "
      "| d at e8 t1.5 (pp) | z | Spearman(w_eff, d) over 16 arms |")
    A("|---|---|---|---|---|---|---|---|---|---|")
    for (be, prop, w, mono, da, za, dm, db, zb, rho) in summ:
        A("| %s | %s | %d | %s | %s | %+.2f | %s | %s | %+.2f | %+.2f |"
          % (be, prop, w, "yes" if mono else "**no**", pp(da), za, pp(dm), pp(db), zb, rho))
    A("")
    n_mono = sum(1 for s in summ if s[3])
    n_neg = sum(1 for s in summ if s[7] < 0)
    n_negsig = sum(1 for s in summ if s[8] <= -ZBAR)
    n_possig = sum(1 for s in summ if s[5] >= ZBAR)
    A("- tau_mult 0.5 row non-decreasing in eta (and >= 0 at eta = 1): **%d of 12** grids." % n_mono)
    A("- e8 t0.5 above the eta = 0 cell at z >= %.2f: **%d of 12**." % (ZBAR, n_possig))
    A("- e8 t1.5 below the eta = 0 cell: **%d of 12**; at z <= -%.2f: **%d of 12**." % (n_neg, ZBAR, n_negsig))
    A("- These are single contrasts against eta = 0, not a max over the 16 rungs; a claim "
      "that *some* rung beat plug needs the max-over-16 correction the protocol names "
      "(section 6.2).")
    A("")
    mono_w = {w: sum(1 for s in summ if s[3] and s[2] == w) for w in (1, 4)}
    head_txt = (
        "**What the grid does and does not show.** At fixed w, in-band tracks the **measured** "
        "deviation gain w_eff: Spearman %.2f to %.2f across the 16 BDG rungs, in all 12 grids. "
        "w_eff > 1 contracts the batch harder than plug and w_eff < 1 less; where it lands "
        "depends on how far the batch spread already sits from the setpoint, so tau_mult "
        "does not set its sign alone (at w = 4 plug has already narrowed the batch, and "
        "tau_mult 0.75 gives w_eff < 1). The tau_mult 0.5 row rises with eta in **%d of 6 "
        "grids at w = 1 and %d of 6 at w = 4**; the tau_mult 1.5 row ends below eta = 0 in "
        "%d of 12. So the robust half of the README's \"sign reversal\" is the loss side. What "
        "the grid does establish is that the gain is carried by the **deviation term's "
        "weight, not by the global strength w**, which the headline cannot separate. It does "
        "**not** show that the *feedback* is necessary: a fixed w_eff "
        % (min(s[9] for s in summ), max(s[9] for s in summ), mono_w[1], mono_w[4], n_neg))
    A(head_txt +
      "schedule is not in the grid, and BDG_REVIEW.md found that replaying the loop's own "
      "schedule on another seed recovers 69.5-96 % of it. The e8 t0.5 rungs also cost "
      "chemistry (column above) and several are clip-heavy (V3_RESULTS_ABL_w*.md).")
    A("")
    # eta = 0 control against the headline's plug
    A("**The eta = 0 control.** `bdg_e0t1` (ablation, w = 1) against `plug` (headline), "
      "same n and seeds, max |d| over properties and seeds:")
    A("")
    A("| backend | max abs d in_band | max abs d mol_stab | same-seed re-runs: max abs d in_band | max abs d mol_stab |")
    A("|---|---|---|---|---|")
    for be in ("fm", "equifm"):
        mi = ms = ri = rs = 0.0
        for prop in PROPS:
            for x, y in zip(abl[(be, 1)][(prop, "bdg_e0t1")], head[be][(prop, "plug")]):
                mi = max(mi, abs(x["in_band_fraction"] - y["in_band_fraction"]))
                ms = max(ms, abs(x["mol_stability"] - y["mol_stability"]))
            # the headline's two BDG arms also run in the ablation at w = 1, same
            # n and seeds: identical configurations, so they are re-runs
            for arm in BDG_HEAD:
                for x, y in zip(abl[(be, 1)][(prop, arm)], head[be][(prop, arm)]):
                    ri = max(ri, abs(x["in_band_fraction"] - y["in_band_fraction"]))
                    rs = max(rs, abs(x["mol_stability"] - y["mol_stability"]))
        A("| %s | %.2e | %.2e | %.2e | %.2e |" % (be, mi, ms, ri, rs))
    A("")
    A("The last two columns compare `bdg_e4t0.5` and `bdg_e4t1`, which run at w = 1 in "
      "**both** the headline and the ablation with the same n and seeds, so each pair is a "
      "re-run of one configuration. fm is bit-exact. **equifm is not**: a re-run moves "
      "in-band by up to the figure shown, which is the same order as equifm's per-cell "
      "BDG - plug differences in section 1 (+0.25 to +1.38 pp). The README attributes this "
      "to EquiFM's sampler being non-deterministic on GPU. So equifm's error bars carry "
      "run-to-run noise on top of seed-to-seed noise, and the binomial se understates them.")
    A("")

    # ------------------------------------------------------------ 4. Betty
    A("## 4. Blade (n = 2000) against Betty (n = 5000)")
    A("")
    A("Two v3 headline runs now exist, on different clusters, same seeds, different n. "
      "**equifm uses TFG's pair in both**, so every equifm row is directly comparable. "
      "**fm is not**: Betty's fm cells predate the per-backend pair and use TFG's pair, "
      "blade's use ours. The pair is the guide f_A **and** the oracle f_B, so on fm the "
      "two runs **steer with different networks** and score in different bands; the cells "
      "record it (Betty: `guide TFG tf_predict_*`, blade: `guide ours weights/f_A_*.pt`). "
      "Only fm's `unguided` rows, which use no guide, are a like-for-like check there "
      "(of the generator).")
    A("")
    gm = lambda cells: sorted({(r.get("prov") or {}).get("gen_md5", "?")[:8]
                               for rs in cells.values() for r in rs})
    A("**The fm generator file differs, the network does not.** Betty loaded `fm_last.pt` "
      "(md5 `%s`), blade `fm_ema.pt` (md5 `%s`); both cells record \"EMA\", epoch 1500, and "
      "weights/README.md says `fm_ema.pt` is `fm_last.pt`'s EMA weights with the optimiser "
      "state stripped. The unguided rows below agree, as they should. equifm is md5 `%s` "
      "in both runs." % (", ".join(gm(betty["fm"])), ", ".join(gm(head["fm"])),
                        ", ".join(gm(head["equifm"]))))
    A("")
    A("| backend | delta (mu, alpha, gap) blade | Betty |")
    A("|---|---|---|")
    for be in ("fm", "equifm"):
        db = ", ".join("%.5f" % head[be][(p, "unguided")][0]["delta"] for p in PROPS)
        dt = ", ".join("%.5f" % betty[be][(p, "unguided")][0]["delta"] for p in PROPS)
        A("| %s | %s | %s |" % (be, db, dt))
    A("")
    common = [a for a in ("unguided", "plug", "tmpd", "lgd_mc", "tfg") + BDG_HEAD]
    A("| backend | prop | arm | in_band blade / Betty | z | mol_stab blade / Betty | z |")
    A("|---|---|---|---|---|---|---|")
    flags_ib, flags_ms, n_ib, n_ms = [], [], 0, 0
    for be in ("fm", "equifm"):
        for prop in PROPS:
            for arm in (common if be == "equifm" else ("unguided",)):
                a, b = P(head[be], prop, arm), P(betty[be], prop, arm)
                zm = zdiff(a["mol_stability"], b["mol_stability"], a["N"], b["N"])
                n_ms += 1
                if abs(zm) >= ZBAR:
                    flags_ms.append((be, prop, arm, zm))
                if be == "equifm":
                    zi = zdiff(a["in_band_fraction"], b["in_band_fraction"], a["N"], b["N"])
                    n_ib += 1
                    if abs(zi) >= ZBAR:
                        flags_ib.append((be, prop, arm, zi))
                    ib = "%.4f / %.4f | %+.2f" % (a["in_band_fraction"], b["in_band_fraction"], zi)
                else:
                    ib = "(band differs) | --"
                A("| %s | %s | `%s` | %s | %.4f / %.4f | %+.2f |"
                  % (be, prop, arm, ib, a["mol_stability"], b["mol_stability"], zm))
    A("")
    A("- equifm in-band, blade vs Betty: **%d of %d** (prop, arm) rows differ at |z| >= %.2f%s."
      % (len(flags_ib), n_ib, ZBAR,
         (": " + "; ".join("%s/`%s` %+.2f" % (p, a, z) for (_b, p, a, z) in flags_ib)) if flags_ib else ""))
    A("- Molecule stability (equifm, all arms; fm, `unguided` only): **%d of %d** rows "
      "differ at |z| >= %.2f%s."
      % (len(flags_ms), n_ms, ZBAR,
         (": " + "; ".join("%s/%s/`%s` %+.2f" % (b, p, a, z) for (b, p, a, z) in flags_ms)) if flags_ms else ""))
    A("")
    A("**BDG minus plug, continuous in-band, in both runs.** On fm the two runs used "
      "different guide networks and bands, so fm rows are two different experiments and "
      "only their signs are set side by side:")
    A("")
    A("| backend | prop | arm | blade d (pp) | Betty d (pp) | same sign |")
    A("|---|---|---|---|---|---|")
    agree = tot = 0
    for be in ("fm", "equifm"):
        for prop in PROPS:
            for arm in BDG_HEAD:
                d1 = P(head[be], prop, arm)["in_band_fraction"] - P(head[be], prop, "plug")["in_band_fraction"]
                d2 = P(betty[be], prop, arm)["in_band_fraction"] - P(betty[be], prop, "plug")["in_band_fraction"]
                same = (d1 > 0) == (d2 > 0)
                agree += same
                tot += 1
                A("| %s | %s | `%s` | %s | %s | %s |" % (be, prop, arm, pp(d1), pp(d2), "yes" if same else "**no**"))
    A("")
    A("- Same sign in **%d of %d**." % (agree, tot))
    A("")
    A("## 5. What is still missing")
    A("")
    A("- **Useful yield on the blade cells**, paired per molecule (McNemar), which is how "
      "the Betty run was read (V3_BETTY_PAIRED.md). It needs the `*.permol.pt` sidecars, "
      "which stay on blade. On blade: "
      "`python proj1/scripts/v3_paired.py --n 2000 --backends fm,equifm "
      "--md-out docs/results/V3_BLADE_PAIRED.md`.")
    A("- **A paired reading of section 3's grid.** Its contrasts are unpaired against "
      "eta = 0 and single, not max-over-16; `v3_paired.py --stage v3abl --w 1` (and 4) "
      "on blade gives the paired one.")

    out = NL.join(L) + NL
    print(out)
    if args.md_out:
        with open(args.md_out, "w", encoding="utf-8", newline="\n") as f:
            f.write(out)
        print("wrote " + args.md_out, file=sys.stderr)


if __name__ == "__main__":
    main()
