"""The same M2 arms at both guidance windows, per property.

    python proj1/m2/m2_window_compare.py --md-out docs/results/M2_WINDOW_COMPARISON.md

WHY THIS PAGE EXISTS. Until 29 Sep the only cpg cells were at t >= 0.5, so the
window argument was demonstrated on gc alone and `tab:m2` paired a gc column at
t >= 0.3 with a cpg column at t >= 0.5. With the 96-cell t >= 0.3 suite both
properties now exist at both windows, and the comparison they make possible is
the point of this page:

  BDG's sign against plug FLIPS with the window on cpg (+16.83 pp at t >= 0.5,
  -4.88 pp at t >= 0.3) while it GROWS on gc (+2.32 -> +7.08 pp).

The mechanism is visible in the same table: opening the window is worth +39.8 pp
to plug on cpg but only +18.1 pp to BDG, so plug overtakes. On gc the ordering
is the other way (+16.2 to plug, +20.9 to BDG) and BDG's lead widens. BDG and an
earlier window are COMPLEMENTS on gc and SUBSTITUTES on cpg.

Reads only committed cells. Writes one markdown file. No GPU, no model.
"""
from __future__ import annotations

import argparse
import collections
import glob
import json
import os
import statistics as st

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

# The stage does NOT determine the window: `m2win` holds a win0.2 probe as well
# as the 96-cell win0.3 suite. So cells are grouped by the window they RECORD,
# and the stage only says which tree to read. WINDOWS lists the two this page
# compares; anything else in the trees is counted and reported, not averaged in.
STAGES = ("m2", "m2win")
WINDOWS = (0.5, 0.3)
ARMS = ["unguided", "plug", "tmpd", "lgd_mc", "tfg_mc",
        "bdg_e0t1", "bdg_e4t0.5", "bdg_e4t1"]
PROPS = ["gc", "cpg"]
NL = "\n"


def arm_key(r):
    """`bdg` carries its grid point in `variant`; every other arm is its name."""
    a = r["arm"]
    v = r.get("variant")
    return a + ("_" + v if a == "bdg" and v not in (None, "", "-") else "")


def load(n):
    rows, other = [], collections.Counter()
    for stage in STAGES:
        pat = os.path.join(ROOT, "results", "m2", stage, "n%d" % n, "seed*", "*.json")
        for f in glob.glob(pat):
            r = json.load(open(f, encoding="utf-8"))
            win = round(float(r["t_min_guide"]), 2)
            if win not in WINDOWS:
                other[win] += 1          # e.g. the single-seed win0.2 probe
                continue
            r["_stage"], r["_win"] = stage, win
            rows.append(r)
    if not rows:
        raise SystemExit("no cells at windows %s under results/m2/{m2,m2win}/n%d"
                         % (WINDOWS, n))
    return rows, other


def main():
    ap = argparse.ArgumentParser(description=__doc__.split(NL)[0])
    ap.add_argument("--n", type=int, default=2000)
    ap.add_argument("--w", type=float, default=4.0)
    ap.add_argument("--md-out", default="")
    a = ap.parse_args()

    rows, other = load(a.n)
    g = collections.defaultdict(list)
    for r in rows:
        g[(r["prop"], r["_win"], r["w"], arm_key(r))].append(r)

    def cell(p, win, w, arm, field="in_band_fraction", scale=100.0):
        v = [x[field] * scale for x in g.get((p, win, w, arm), [])]
        if not v:
            return None, None, 0
        return st.mean(v), (st.stdev(v) if len(v) > 1 else 0.0), len(v)

    A = []
    A.append("# Modality 2: the same arms at both guidance windows")
    A.append("")
    A.append("Generated by `proj1/m2/m2_window_compare.py`. Do not hand-edit; re-run it:")
    A.append("")
    A.append("```")
    A.append("python proj1/m2/m2_window_compare.py --md-out docs/results/M2_WINDOW_COMPARISON.md")
    A.append("```")
    A.append("")
    seeds = sorted({r["seed"] for r in rows})
    ck = sorted({os.path.basename(str(r.get("ckpt", "?"))) for r in rows})
    A.append("Sources: `results/m2/m2/` (t >= 0.5) and `results/m2/m2win/` (t >= 0.3), "
             "n = %d, w = %g, seeds %s, checkpoint %s. Every other axis is identical "
             "between the two stages: batch 500, NFE 100, q50, clip 1.0, "
             "delta_ratio 0.16."
             % (a.n, a.w, ", ".join(str(s) for s in seeds), "/".join(ck)))
    if other:
        A.append("Set aside (a different window, not part of this comparison): %s."
                 % ", ".join("%d cell%s at t >= %g" % (v, "" if v == 1 else "s", k)
                             for k, v in sorted(other.items())))
        A.append("")
    A.append("> ### The headline: BDG's sign against plug depends on the property")
    A.append(">")
    A.append("> | property | t >= 0.5 | t >= 0.3 |")
    A.append("> |---|---|---|")
    flips = {}
    for p in PROPS:
        r = []
        for win in (0.5, 0.3):
            pl, _, _ = cell(p, win, a.w, "plug")
            bd, _, _ = cell(p, win, a.w, "bdg_e4t0.5")
            r.append(None if (pl is None or bd is None) else bd - pl)
        flips[p] = r
        A.append("> | `%s` | %s | %s |"
                 % (p, "--" if r[0] is None else "**%+.2f pp**" % r[0],
                    "--" if r[1] is None else "**%+.2f pp**" % r[1]))
    A.append(">")
    A.append("> On `cpg` the sign **flips**. \"BDG helps on Modality 2\" cannot be "
             "stated without naming the property and the window.")
    A.append("")

    # ---- per property, both windows, every arm ----------------------------
    for p in PROPS:
        A.append("## %s" % p)
        A.append("")
        A.append("| arm | t >= 0.5 | t >= 0.3 | what the window is worth |")
        A.append("|---|---|---|---|")
        for arm in ARMS:
            m5, s5, n5 = cell(p, 0.5, a.w, arm)
            m3, s3, n3 = cell(p, 0.3, a.w, arm)
            f = lambda m, s: "--" if m is None else "%.2f ±%.2f" % (m, s)
            d = ("--" if (m5 is None or m3 is None) else "%+.2f pp" % (m3 - m5))
            A.append("| `%s` | %s | %s | %s |" % (arm, f(m5, s5), f(m3, s3), d))
        A.append("")
        pl5, _, _ = cell(p, 0.5, a.w, "plug")
        pl3, _, _ = cell(p, 0.3, a.w, "plug")
        bd5, _, _ = cell(p, 0.5, a.w, "bdg_e4t0.5")
        bd3, _, _ = cell(p, 0.3, a.w, "bdg_e4t0.5")
        if None not in (pl5, pl3, bd5, bd3):
            A.append("The window is worth **%+.2f pp to plug** and **%+.2f pp to BDG** "
                     "here, so BDG's margin goes **%+.2f pp -> %+.2f pp**."
                     % (pl3 - pl5, bd3 - bd5, bd5 - pl5, bd3 - pl3))
            A.append("")

    # ---- chemistry, so in-band is never read alone ------------------------
    A.append("## Chemistry at t >= 0.3, so no in-band number is read alone")
    A.append("")
    A.append("| property | arm | in-band | k-mer JSD | diversity | clip % |")
    A.append("|---|---|---|---|---|---|")
    for p in PROPS:
        for arm in ARMS:
            ib, _, n = cell(p, 0.3, a.w, arm)
            if ib is None:
                continue
            kj, _, _ = cell(p, 0.3, a.w, arm, "kmer_js", 1.0)
            dv, _, _ = cell(p, 0.3, a.w, arm, "diversity", 1.0)
            cl, _, _ = cell(p, 0.3, a.w, arm, "clipped_sample_steps", 1.0)
            denom = a.n * 100.0 / 500.0 * 100.0     # controllers x guided steps
            A.append("| %s | `%s` | %.2f | %.5f | %.4f | %.1f |"
                     % (p, arm, ib, kj, dv, 100.0 * cl / denom))
    A.append("")

    A.append("## Reading this page")
    A.append("")
    A.append("1. **Never pool or compare in-band across the two properties.** "
             "`cpg`'s band is quantum-floored at 0.60 sd against `gc`'s 0.16 "
             "(`delta = max(0.16*s, 4.4*quantum)`), so unguided already sits "
             "in band 50.2 %% of the time on `cpg` against 14.0 %% on `gc`. The "
             "two are not on one difficulty scale.")
    A.append("2. **BDG's mechanism is contraction**, which has little to gain "
             "against a band that wide and something to lose as the batch mean "
             "drifts. That is the measured reason the sign flips.")
    A.append("3. **`bdg_e4t1` is catastrophic on both** properties, so the "
             "setpoint sign-reversal holds and `tau_mult = 0.5` carries the method.")
    A.append("4. **The compare set degenerates at t >= 0.5 on BOTH properties** "
             "(`tmpd` and `lgd_mc` are bit-identical to `plug` there). That is a "
             "theorem about the residual endpoint variance collapsing, not a "
             "property of the observable -- see `docs/methods/`.")
    A.append("")

    out = NL.join(A) + NL
    if a.md_out:
        path = a.md_out if os.path.isabs(a.md_out) else os.path.join(ROOT, a.md_out)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(out)
        print("wrote %s (%d lines)" % (path, len(A)))
    else:
        print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
